---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end.canary
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        dynatrace/instrument: "false"
        pipeline.stage: prod-canary
        pipeline.build: 1.5.0.3486
        pipeline.project: sockshop
        support.contact: "jane.smith@sockshop.com"
        support.channel: "#support-sockshop-frontend"
      labels:
        app: front-end.canary
        stage: prod
        release: canary
        version: "1.5"
        tier: "frontend"
        product: "sockshop"
    spec:
      containers:
      - name: front-end
        image: dynatracesockshop/front-end:0.5.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      nodeSelector:
        beta.kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: front-end-canary
  labels:
    app: front-end.canary
    namespace: production
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: front-end.canary
  type: LoadBalancer
